version: '3'

services:
#  jenkins:
#    container_name: jenkins
#    build:
#      context: ./jenkins
#      dockerfile: Dockerfile
#    image: jenkins
#    restart: always
#    volumes:
#      - $PWD/jenkins:/var/jenkins_home
#      - /var/run/docker.sock:/var/run/docker.sock
#      - /usr/bin/docker:/usr/bin/docker
#    ports:
#      - 8080:8080
#      - 5000:5000
#    networks:
#      - backend
#    depends_on:
#      - gateway
#      - api
#      - frontend
  gateway:
    container_name: gateway
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: gateway
    restart: always
    volumes:
      - $PWD/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - api
    ports:
      - 8081:80
      - 443:443
    networks:
      - backend

  frontend:
    container_name: frontend
    restart: always
    volumes:
      - $PWD/frontend/dist:/var/www
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend
    ports:
      - 3000:3000
    networks:
      - backend

  api:
    container_name: api
    restart: always
    build:
      context: ./api
      dockerfile: Dockerfile
    image: api
    command: npm run prod
    hostname: api
    volumes:
      - $PWD/api:/app
      - /app/node_modules
    ports:
      - 4000:4000
    networks:
      - backend
    environment:
      - MYSQL_HOST=mysql
    depends_on:
      - mysql
    links:
      - mysql:mysql
  mysql:
    container_name: mysql
    image: mysql:5.7
    hostname: mysql
    restart: always
    volumes:
      - $PWD/mysql:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=test"
      - "MYSQL_USER=test"
      - "MYSQL_PASSWORD=test"
      - "MYSQL_ROOT_PASSWORD=123456"
    ports:
      - "3306:3306"
    networks:
      - backend
networks:
  backend: