version: '3'

services:
  frontend:
    container_name: frontend
    restart: always
    volumes:
      - $PWD/frontend/dist:/var/www
      - $PWD/frontend/nginx/nginx.conf:/etc/nginx/nginx.conf
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend
    ports:
      - 3000:3000
    networks:
      - backend
networks:
  backend: