version: '3'

services:
  nginx_gateway: 
    container_name: nginx_gateway
    entrypoint: ["/bin/bash"]
    command: ["./wait-for-it.sh", "nginx_frontend:3000", "--",
              "./wait-for-it.sh", "nginx_api:4000", "--", 
              "nginx","-g","daemon off;"]
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    volumes:
      - $PWD/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nginx_frontend
      - nginx_api
    ports:
      - 8081:80
      - 443:443
    networks:
      - backend

  nginx_frontend:
    container_name: nginx_frontend
    restart: always
    volumes:
      - $PWD/frontend/dist:/var/www
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - backend

  nginx_api: 
    container_name: nginx_api
    restart: always
    build:
      context: ./api
      dockerfile: Dockerfile
    command: npm run prod
    volumes:
      - $PWD/api:/app
      - /app/node_modules
    depends_on:
      - mysql
    ports:
      - 4000:4000
    networks:
      - backend
  mysql:
    image: mysql:5.7
    volumes:
      - $PWD/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test

networks:
  backend: